sonar.projectKey=app-sonar
sonar.projectName=App Sonar Demo
sonar.organization=davidelezg-lab
sonar.sources=.
sonar.host.url=https://sonarcloud.io/
sonar.login=d92535504cea064186f549b9bc5a525c2ea15f74