name: Pipeline con Sonar

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Sonar
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=app-sonar \
            -Dsonar.organization=davidelezg-lab \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Ejecutar los tests
        run: npm test
