name: Pipeline avanzado

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Tests
        run: npx jest --coverage

      - name: Sonar
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=app-sonar \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Simular deploy
        run: echo "Deploy OK"
